title: 张进程
email: 415397228@qq.com
description: 张进程个人技术，生活。PHP，Go，Web... 
baseurl: ""
url: "https://blog.memosa.cn"
twitter_username: 不害羞滴含羞草
github_username:  aaronzjc

plugins:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock  
pagination:
  enabled: true
  debug: false
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 7
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  extension: html
  indexpage: 'index'