# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 张进程
email: 415397228@qq.com
description: > # 个人博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://memosa.cn/"  #the base hostname & protocol for your site
# url: "http:/localhost:4000"
twitter_username: 不害羞滴含羞草
github_username:  aaronzjc

# gem files
gems: [jekyll-paginate]

# Build settings
markdown: kramdown

# pagination
paginate: 10
paginate_path: "/blog/page:num/"
