title: 张进程
email: 415397228@qq.com
description: 张进程个人技术，生活。PHP，Go，Web... # 个人博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.memosa.cn"  #the base hostname & protocol for your site
twitter_username: 不害羞滴含羞草
github_username:  aaronzjc

# gem files
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown

# pagination
paginate: 7
paginate_path: "/blog/page/:num"
