# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    branches: [ master ]

jobs:
  jekyll:
    name: Build and deploy My Blog
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: release blog
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: aaronzjc/blog
        target: dist
        tags: latest
    - name: setup ktl
      uses: azure/setup-kubectl@v1
      id: install
    - name: deploy
      run: |
        cat << EOF > kube-config
        ${{ secrets.KUBECONF }}
        EOF
        export KUBECONFIG=$(pwd)/kube-config
        curl -o blog.yml https://raw.githubusercontent.com/aaronzjc/k3s/main/Deployment/blog.yml
        kubectl rollout restart -f blog.yml -n k3s-apps
